import { randomUUID } from "node:crypto";
import { getDatabase } from "../db/index.js";
import type { StoryBewertung, StoryBild, StoryProjekt } from "./types.js";

interface ProjektRow { id:string; name:string; status:"entwurf"|"fertig"; konfiguration_json:string; erstellt_am:string; aktualisiert_am:string }
interface BildRow { id:string; projekt_id:string; dateiname:string; mime_type:string; groesse_bytes:number; sha256:string; storage_path:string; sortierung:number; konfiguration_json:string; erstellt_am:string }
interface BewertungRow { id:string; name:string; text:string; sterne:number; quelle:string; erstellt_am:string; aktualisiert_am:string }
const json = (value: string) => { try { return JSON.parse(value) as Record<string, unknown>; } catch { return {}; } };
const image = (r: BildRow): StoryBild => ({ id:r.id, projektId:r.projekt_id, dateiname:r.dateiname, mimeType:r.mime_type, groesseBytes:r.groesse_bytes, sortierung:r.sortierung, konfiguration:json(r.konfiguration_json), erstelltAm:r.erstellt_am });
const review = (r: BewertungRow): StoryBewertung => ({ id:r.id, name:r.name, text:r.text, sterne:r.sterne, quelle:r.quelle, erstelltAm:r.erstellt_am, aktualisiertAm:r.aktualisiert_am });
function project(r: ProjektRow): StoryProjekt { return { id:r.id, name:r.name, status:r.status, konfiguration:json(r.konfiguration_json), bilder:listImages(r.id), erstelltAm:r.erstellt_am, aktualisiertAm:r.aktualisiert_am }; }
export function listProjects() { return (getDatabase().prepare("SELECT * FROM whatsapp_story_projekt ORDER BY aktualisiert_am DESC").all() as ProjektRow[]).map(project); }
export function getProject(id:string) { const r=getDatabase().prepare("SELECT * FROM whatsapp_story_projekt WHERE id=?").get(id) as ProjektRow|undefined; return r?project(r):null; }
export function createProject(name:string) { const id=randomUUID(); getDatabase().prepare("INSERT INTO whatsapp_story_projekt(id,name) VALUES(?,?)").run(id,name.trim()||"Neue Story"); return getProject(id)!; }
export function updateProject(id:string, patch:{name?:string;status?:"entwurf"|"fertig";konfiguration?:Record<string,unknown>}) { const old=getProject(id); if(!old)return null; getDatabase().prepare("UPDATE whatsapp_story_projekt SET name=?,status=?,konfiguration_json=?,aktualisiert_am=datetime('now') WHERE id=?").run(patch.name?.trim()||old.name,patch.status??old.status,JSON.stringify(patch.konfiguration??old.konfiguration),id); return getProject(id); }
export function deleteProject(id:string) { const raws=getDatabase().prepare("SELECT storage_path,sha256 FROM whatsapp_story_bild WHERE projekt_id=?").all(id) as Pick<BildRow,"storage_path"|"sha256">[]; const result=getDatabase().prepare("DELETE FROM whatsapp_story_projekt WHERE id=?").run(id); return { deleted:result.changes>0, files:raws }; }
export function listImages(projectId:string) { return (getDatabase().prepare("SELECT * FROM whatsapp_story_bild WHERE projekt_id=? ORDER BY sortierung,id").all(projectId) as BildRow[]).map(image); }
export function getImageRaw(id:string) { return getDatabase().prepare("SELECT * FROM whatsapp_story_bild WHERE id=?").get(id) as BildRow|undefined; }
export function addImage(input:{projectId:string;dateiname:string;mimeType:string;groesseBytes:number;sha256:string;storagePath:string}) { const id=randomUUID(); const max=getDatabase().prepare("SELECT COALESCE(MAX(sortierung),-1) AS n FROM whatsapp_story_bild WHERE projekt_id=?").get(input.projectId) as {n:number}; getDatabase().prepare("INSERT INTO whatsapp_story_bild(id,projekt_id,dateiname,mime_type,groesse_bytes,sha256,storage_path,sortierung) VALUES(?,?,?,?,?,?,?,?)").run(id,input.projectId,input.dateiname,input.mimeType,input.groesseBytes,input.sha256,input.storagePath,max.n+1); return image(getImageRaw(id)!); }
export function updateImage(id:string, patch:{sortierung?:number;konfiguration?:Record<string,unknown>}) { const old=getImageRaw(id); if(!old)return null; getDatabase().prepare("UPDATE whatsapp_story_bild SET sortierung=?,konfiguration_json=? WHERE id=?").run(patch.sortierung??old.sortierung,JSON.stringify(patch.konfiguration??json(old.konfiguration_json)),id); return image(getImageRaw(id)!); }
export function deleteImage(id:string) { const raw=getImageRaw(id); if(!raw)return null; getDatabase().prepare("DELETE FROM whatsapp_story_bild WHERE id=?").run(id); return raw; }
export function imageRefs(sha:string) { return (getDatabase().prepare("SELECT COUNT(*) AS n FROM whatsapp_story_bild WHERE sha256=?").get(sha) as {n:number}).n; }
export function listReviews() { return (getDatabase().prepare("SELECT * FROM whatsapp_story_bewertung ORDER BY name COLLATE NOCASE").all() as BewertungRow[]).map(review); }
export function getReview(id:string) { const r=getDatabase().prepare("SELECT * FROM whatsapp_story_bewertung WHERE id=?").get(id) as BewertungRow|undefined; return r?review(r):null; }
export function createReview(input:{name:string;text:string;sterne:number;quelle?:string}) { const id=randomUUID(); getDatabase().prepare("INSERT INTO whatsapp_story_bewertung(id,name,text,sterne,quelle) VALUES(?,?,?,?,?)").run(id,input.name.trim(),input.text.trim(),input.sterne,input.quelle??"manuell"); return getReview(id)!; }
export function updateReview(id:string,input:{name?:string;text?:string;sterne?:number}) { const old=getReview(id); if(!old)return null; getDatabase().prepare("UPDATE whatsapp_story_bewertung SET name=?,text=?,sterne=?,aktualisiert_am=datetime('now') WHERE id=?").run(input.name?.trim()||old.name,input.text?.trim()||old.text,input.sterne??old.sterne,id); return getReview(id); }
export function deleteReview(id:string) { return getDatabase().prepare("DELETE FROM whatsapp_story_bewertung WHERE id=?").run(id).changes>0; }
