export type StoryLayout = "einzel" | "landschaft" | "vorher-nachher";
export type ReviewPosition = "oben-links" | "oben-rechts" | "unten-links" | "unten-rechts";
export interface CropState { zoom:number; x:number; y:number }
export interface StoryPhoto { id:string; file:File; url:string; name:string; layout:StoryLayout; pairId?:string; crop:CropState; title:string; reviewId?:string; reviewPosition:ReviewPosition; reviewOffset:number }
export interface StoryReview { id:string; name:string; text:string; stars:number }
export interface StoryOptions { useReviews:boolean; reviewEnding:boolean; googleEnding:boolean; googleUrl:string }
export const STORY_WIDTH=1080;
export const STORY_HEIGHT=1920;
export const DEFAULT_CROP:CropState={zoom:1,x:0,y:0};

const imageCache=new Map<string,Promise<HTMLImageElement>>();
function loadImage(src:string){let cached=imageCache.get(src);if(!cached){cached=new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=src;});imageCache.set(src,cached);}return cached;}
function rounded(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.clip();}
async function drawCover(ctx:CanvasRenderingContext2D,src:string,x:number,y:number,w:number,h:number,crop:CropState){const image=await loadImage(src);const base=Math.max(w/image.naturalWidth,h/image.naturalHeight)*crop.zoom;const dw=image.naturalWidth*base,dh=image.naturalHeight*base;ctx.save();rounded(ctx,x,y,w,h,28);ctx.drawImage(image,x+(w-dw)/2+crop.x,y+(h-dh)/2+crop.y,dw,dh);ctx.restore();}
function drawReview(ctx:CanvasRenderingContext2D,review:StoryReview,pos:ReviewPosition,offset:number){const w=690,h=238;const x=pos.endsWith("rechts")?330:60;const y=(pos.startsWith("oben")?610:1430)+offset;ctx.save();ctx.fillStyle="rgba(255,255,255,.96)";ctx.shadowColor="rgba(0,0,0,.35)";ctx.shadowBlur=24;ctx.beginPath();ctx.roundRect(x,y,w,h,24);ctx.fill();ctx.shadowBlur=0;ctx.fillStyle="#111827";ctx.font="700 34px Arial";ctx.fillText(review.name,x+34,y+50);ctx.fillStyle="#f5b301";ctx.font="32px Arial";ctx.fillText("★".repeat(review.stars),x+34,y+91);ctx.fillStyle="#374151";ctx.font="26px Arial";const words=review.text.split(/\s+/);let line="",yy=y+135;for(const word of words){const next=`${line}${line?" ":""}${word}`;if(ctx.measureText(next).width>w-68){ctx.fillText(line,x+34,yy);line=word;yy+=34;if(yy>y+h-24)break;}else line=next;}if(yy<=y+h-24)ctx.fillText(line,x+34,yy);ctx.restore();}
export async function renderStory(canvas:HTMLCanvasElement,templateUrl:string,photo:StoryPhoto,photos:StoryPhoto[],review?:StoryReview){canvas.width=STORY_WIDTH;canvas.height=STORY_HEIGHT;const ctx=canvas.getContext("2d");if(!ctx)return;const template=await loadImage(templateUrl);ctx.drawImage(template,0,0,STORY_WIDTH,STORY_HEIGHT);if(photo.layout==="landschaft"){await drawCover(ctx,photo.url,70,585,940,500,photo.crop);const pair=photos.find(p=>p.id===photo.pairId);if(pair)await drawCover(ctx,pair.url,70,1120,940,500,pair.crop);}else if(photo.layout==="vorher-nachher"){const pair=photos.find(p=>p.id===photo.pairId);await drawCover(ctx,photo.url,55,650,475,920,photo.crop);if(pair)await drawCover(ctx,pair.url,550,650,475,920,pair.crop);ctx.font="700 38px Arial";ctx.textAlign="center";ctx.fillStyle="#fff";ctx.fillText("VORHER",292,1625);ctx.fillText("NACHHER",787,1625);ctx.textAlign="start";}else await drawCover(ctx,photo.url,70,610,940,1010,photo.crop);if(photo.title){ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font="700 48px Arial";ctx.fillText(photo.title,540,1745);ctx.textAlign="start";}if(review)drawReview(ctx,review,photo.reviewPosition,photo.reviewOffset);}
export async function renderReviewEnding(canvas:HTMLCanvasElement,templateUrl:string,reviews:StoryReview[]){canvas.width=STORY_WIDTH;canvas.height=STORY_HEIGHT;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.drawImage(await loadImage(templateUrl),0,0,STORY_WIDTH,STORY_HEIGHT);ctx.fillStyle="#fff";ctx.font="700 56px Arial";ctx.textAlign="center";ctx.fillText("Das sagen unsere Kunden",540,650);reviews.slice(0,4).forEach((r,i)=>drawReview(ctx,r,i%2?"oben-rechts":"oben-links",i*255));ctx.textAlign="start";}
export async function renderGoogleEnding(canvas:HTMLCanvasElement,templateUrl:string,qrDataUrl?:string){canvas.width=STORY_WIDTH;canvas.height=STORY_HEIGHT;const ctx=canvas.getContext("2d");if(!ctx)return;ctx.drawImage(await loadImage(templateUrl),0,0,STORY_WIDTH,STORY_HEIGHT);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font="700 64px Arial";ctx.fillText("Bewerten Sie uns auf Google",540,800);if(qrDataUrl){const qr=await loadImage(qrDataUrl);ctx.fillStyle="#fff";ctx.beginPath();ctx.roundRect(350,900,380,380,28);ctx.fill();ctx.drawImage(qr,380,930,320,320);}ctx.textAlign="start";}
export function canvasBlob(canvas:HTMLCanvasElement){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error("Bild konnte nicht erstellt werden")),"image/png"));}
