/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WerkzeugeRouteImport } from './routes/werkzeuge'
import { Route as StundenzettelRouteImport } from './routes/stundenzettel'
import { Route as SteuernRouteImport } from './routes/steuern'
import { Route as RechnungenRouteImport } from './routes/rechnungen'
import { Route as ProtokolleRouteImport } from './routes/protokolle'
import { Route as ObjekteRouteImport } from './routes/objekte'
import { Route as KundenRouteImport } from './routes/kunden'
import { Route as EinstellungenRouteImport } from './routes/einstellungen'
import { Route as DokumenteRouteImport } from './routes/dokumente'
import { Route as AngeboteRouteImport } from './routes/angebote'
import { Route as AktivitaetRouteImport } from './routes/aktivitaet'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WerkzeugeIndexRouteImport } from './routes/werkzeuge.index'
import { Route as WerkzeugeUebergabeprotokollRouteImport } from './routes/werkzeuge.uebergabeprotokoll'
import { Route as WerkzeugeSchluesseluebergabeRouteImport } from './routes/werkzeuge.schluesseluebergabe'
import { Route as RechnungenNeuRouteImport } from './routes/rechnungen.neu'
import { Route as RechnungenIdRouteImport } from './routes/rechnungen.$id'
import { Route as ProtokolleIdRouteImport } from './routes/protokolle.$id'
import { Route as ObjekteNeuRouteImport } from './routes/objekte.neu'
import { Route as ObjekteIdRouteImport } from './routes/objekte.$id'
import { Route as KundenNeuRouteImport } from './routes/kunden.neu'
import { Route as KundenIdRouteImport } from './routes/kunden.$id'
import { Route as EinstellungenDatenbankRouteImport } from './routes/einstellungen.datenbank'
import { Route as AngeboteNeuRouteImport } from './routes/angebote.neu'
import { Route as AngeboteIdRouteImport } from './routes/angebote.$id'
import { Route as RechnungenIdBearbeitenRouteImport } from './routes/rechnungen.$id.bearbeiten'
import { Route as ProtokolleIdBearbeitenRouteImport } from './routes/protokolle.$id.bearbeiten'
import { Route as MUploadSessionRouteImport } from './routes/m.upload.$session'
import { Route as AngeboteIdBearbeitenRouteImport } from './routes/angebote.$id.bearbeiten'

const WerkzeugeRoute = WerkzeugeRouteImport.update({
  id: '/werkzeuge',
  path: '/werkzeuge',
  getParentRoute: () => rootRouteImport,
} as any)
const StundenzettelRoute = StundenzettelRouteImport.update({
  id: '/stundenzettel',
  path: '/stundenzettel',
  getParentRoute: () => rootRouteImport,
} as any)
const SteuernRoute = SteuernRouteImport.update({
  id: '/steuern',
  path: '/steuern',
  getParentRoute: () => rootRouteImport,
} as any)
const RechnungenRoute = RechnungenRouteImport.update({
  id: '/rechnungen',
  path: '/rechnungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtokolleRoute = ProtokolleRouteImport.update({
  id: '/protokolle',
  path: '/protokolle',
  getParentRoute: () => rootRouteImport,
} as any)
const ObjekteRoute = ObjekteRouteImport.update({
  id: '/objekte',
  path: '/objekte',
  getParentRoute: () => rootRouteImport,
} as any)
const KundenRoute = KundenRouteImport.update({
  id: '/kunden',
  path: '/kunden',
  getParentRoute: () => rootRouteImport,
} as any)
const EinstellungenRoute = EinstellungenRouteImport.update({
  id: '/einstellungen',
  path: '/einstellungen',
  getParentRoute: () => rootRouteImport,
} as any)
const DokumenteRoute = DokumenteRouteImport.update({
  id: '/dokumente',
  path: '/dokumente',
  getParentRoute: () => rootRouteImport,
} as any)
const AngeboteRoute = AngeboteRouteImport.update({
  id: '/angebote',
  path: '/angebote',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivitaetRoute = AktivitaetRouteImport.update({
  id: '/aktivitaet',
  path: '/aktivitaet',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WerkzeugeIndexRoute = WerkzeugeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WerkzeugeRoute,
} as any)
const WerkzeugeUebergabeprotokollRoute =
  WerkzeugeUebergabeprotokollRouteImport.update({
    id: '/uebergabeprotokoll',
    path: '/uebergabeprotokoll',
    getParentRoute: () => WerkzeugeRoute,
  } as any)
const WerkzeugeSchluesseluebergabeRoute =
  WerkzeugeSchluesseluebergabeRouteImport.update({
    id: '/schluesseluebergabe',
    path: '/schluesseluebergabe',
    getParentRoute: () => WerkzeugeRoute,
  } as any)
const RechnungenNeuRoute = RechnungenNeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => RechnungenRoute,
} as any)
const RechnungenIdRoute = RechnungenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RechnungenRoute,
} as any)
const ProtokolleIdRoute = ProtokolleIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProtokolleRoute,
} as any)
const ObjekteNeuRoute = ObjekteNeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => ObjekteRoute,
} as any)
const ObjekteIdRoute = ObjekteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ObjekteRoute,
} as any)
const KundenNeuRoute = KundenNeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => KundenRoute,
} as any)
const KundenIdRoute = KundenIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => KundenRoute,
} as any)
const EinstellungenDatenbankRoute = EinstellungenDatenbankRouteImport.update({
  id: '/datenbank',
  path: '/datenbank',
  getParentRoute: () => EinstellungenRoute,
} as any)
const AngeboteNeuRoute = AngeboteNeuRouteImport.update({
  id: '/neu',
  path: '/neu',
  getParentRoute: () => AngeboteRoute,
} as any)
const AngeboteIdRoute = AngeboteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AngeboteRoute,
} as any)
const RechnungenIdBearbeitenRoute = RechnungenIdBearbeitenRouteImport.update({
  id: '/bearbeiten',
  path: '/bearbeiten',
  getParentRoute: () => RechnungenIdRoute,
} as any)
const ProtokolleIdBearbeitenRoute = ProtokolleIdBearbeitenRouteImport.update({
  id: '/bearbeiten',
  path: '/bearbeiten',
  getParentRoute: () => ProtokolleIdRoute,
} as any)
const MUploadSessionRoute = MUploadSessionRouteImport.update({
  id: '/m/upload/$session',
  path: '/m/upload/$session',
  getParentRoute: () => rootRouteImport,
} as any)
const AngeboteIdBearbeitenRoute = AngeboteIdBearbeitenRouteImport.update({
  id: '/bearbeiten',
  path: '/bearbeiten',
  getParentRoute: () => AngeboteIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aktivitaet': typeof AktivitaetRoute
  '/angebote': typeof AngeboteRouteWithChildren
  '/dokumente': typeof DokumenteRoute
  '/einstellungen': typeof EinstellungenRouteWithChildren
  '/kunden': typeof KundenRouteWithChildren
  '/objekte': typeof ObjekteRouteWithChildren
  '/protokolle': typeof ProtokolleRouteWithChildren
  '/rechnungen': typeof RechnungenRouteWithChildren
  '/steuern': typeof SteuernRoute
  '/stundenzettel': typeof StundenzettelRoute
  '/werkzeuge': typeof WerkzeugeRouteWithChildren
  '/angebote/$id': typeof AngeboteIdRouteWithChildren
  '/angebote/neu': typeof AngeboteNeuRoute
  '/einstellungen/datenbank': typeof EinstellungenDatenbankRoute
  '/kunden/$id': typeof KundenIdRoute
  '/kunden/neu': typeof KundenNeuRoute
  '/objekte/$id': typeof ObjekteIdRoute
  '/objekte/neu': typeof ObjekteNeuRoute
  '/protokolle/$id': typeof ProtokolleIdRouteWithChildren
  '/rechnungen/$id': typeof RechnungenIdRouteWithChildren
  '/rechnungen/neu': typeof RechnungenNeuRoute
  '/werkzeuge/schluesseluebergabe': typeof WerkzeugeSchluesseluebergabeRoute
  '/werkzeuge/uebergabeprotokoll': typeof WerkzeugeUebergabeprotokollRoute
  '/werkzeuge/': typeof WerkzeugeIndexRoute
  '/angebote/$id/bearbeiten': typeof AngeboteIdBearbeitenRoute
  '/m/upload/$session': typeof MUploadSessionRoute
  '/protokolle/$id/bearbeiten': typeof ProtokolleIdBearbeitenRoute
  '/rechnungen/$id/bearbeiten': typeof RechnungenIdBearbeitenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aktivitaet': typeof AktivitaetRoute
  '/angebote': typeof AngeboteRouteWithChildren
  '/dokumente': typeof DokumenteRoute
  '/einstellungen': typeof EinstellungenRouteWithChildren
  '/kunden': typeof KundenRouteWithChildren
  '/objekte': typeof ObjekteRouteWithChildren
  '/protokolle': typeof ProtokolleRouteWithChildren
  '/rechnungen': typeof RechnungenRouteWithChildren
  '/steuern': typeof SteuernRoute
  '/stundenzettel': typeof StundenzettelRoute
  '/angebote/$id': typeof AngeboteIdRouteWithChildren
  '/angebote/neu': typeof AngeboteNeuRoute
  '/einstellungen/datenbank': typeof EinstellungenDatenbankRoute
  '/kunden/$id': typeof KundenIdRoute
  '/kunden/neu': typeof KundenNeuRoute
  '/objekte/$id': typeof ObjekteIdRoute
  '/objekte/neu': typeof ObjekteNeuRoute
  '/protokolle/$id': typeof ProtokolleIdRouteWithChildren
  '/rechnungen/$id': typeof RechnungenIdRouteWithChildren
  '/rechnungen/neu': typeof RechnungenNeuRoute
  '/werkzeuge/schluesseluebergabe': typeof WerkzeugeSchluesseluebergabeRoute
  '/werkzeuge/uebergabeprotokoll': typeof WerkzeugeUebergabeprotokollRoute
  '/werkzeuge': typeof WerkzeugeIndexRoute
  '/angebote/$id/bearbeiten': typeof AngeboteIdBearbeitenRoute
  '/m/upload/$session': typeof MUploadSessionRoute
  '/protokolle/$id/bearbeiten': typeof ProtokolleIdBearbeitenRoute
  '/rechnungen/$id/bearbeiten': typeof RechnungenIdBearbeitenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aktivitaet': typeof AktivitaetRoute
  '/angebote': typeof AngeboteRouteWithChildren
  '/dokumente': typeof DokumenteRoute
  '/einstellungen': typeof EinstellungenRouteWithChildren
  '/kunden': typeof KundenRouteWithChildren
  '/objekte': typeof ObjekteRouteWithChildren
  '/protokolle': typeof ProtokolleRouteWithChildren
  '/rechnungen': typeof RechnungenRouteWithChildren
  '/steuern': typeof SteuernRoute
  '/stundenzettel': typeof StundenzettelRoute
  '/werkzeuge': typeof WerkzeugeRouteWithChildren
  '/angebote/$id': typeof AngeboteIdRouteWithChildren
  '/angebote/neu': typeof AngeboteNeuRoute
  '/einstellungen/datenbank': typeof EinstellungenDatenbankRoute
  '/kunden/$id': typeof KundenIdRoute
  '/kunden/neu': typeof KundenNeuRoute
  '/objekte/$id': typeof ObjekteIdRoute
  '/objekte/neu': typeof ObjekteNeuRoute
  '/protokolle/$id': typeof ProtokolleIdRouteWithChildren
  '/rechnungen/$id': typeof RechnungenIdRouteWithChildren
  '/rechnungen/neu': typeof RechnungenNeuRoute
  '/werkzeuge/schluesseluebergabe': typeof WerkzeugeSchluesseluebergabeRoute
  '/werkzeuge/uebergabeprotokoll': typeof WerkzeugeUebergabeprotokollRoute
  '/werkzeuge/': typeof WerkzeugeIndexRoute
  '/angebote/$id/bearbeiten': typeof AngeboteIdBearbeitenRoute
  '/m/upload/$session': typeof MUploadSessionRoute
  '/protokolle/$id/bearbeiten': typeof ProtokolleIdBearbeitenRoute
  '/rechnungen/$id/bearbeiten': typeof RechnungenIdBearbeitenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aktivitaet'
    | '/angebote'
    | '/dokumente'
    | '/einstellungen'
    | '/kunden'
    | '/objekte'
    | '/protokolle'
    | '/rechnungen'
    | '/steuern'
    | '/stundenzettel'
    | '/werkzeuge'
    | '/angebote/$id'
    | '/angebote/neu'
    | '/einstellungen/datenbank'
    | '/kunden/$id'
    | '/kunden/neu'
    | '/objekte/$id'
    | '/objekte/neu'
    | '/protokolle/$id'
    | '/rechnungen/$id'
    | '/rechnungen/neu'
    | '/werkzeuge/schluesseluebergabe'
    | '/werkzeuge/uebergabeprotokoll'
    | '/werkzeuge/'
    | '/angebote/$id/bearbeiten'
    | '/m/upload/$session'
    | '/protokolle/$id/bearbeiten'
    | '/rechnungen/$id/bearbeiten'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aktivitaet'
    | '/angebote'
    | '/dokumente'
    | '/einstellungen'
    | '/kunden'
    | '/objekte'
    | '/protokolle'
    | '/rechnungen'
    | '/steuern'
    | '/stundenzettel'
    | '/angebote/$id'
    | '/angebote/neu'
    | '/einstellungen/datenbank'
    | '/kunden/$id'
    | '/kunden/neu'
    | '/objekte/$id'
    | '/objekte/neu'
    | '/protokolle/$id'
    | '/rechnungen/$id'
    | '/rechnungen/neu'
    | '/werkzeuge/schluesseluebergabe'
    | '/werkzeuge/uebergabeprotokoll'
    | '/werkzeuge'
    | '/angebote/$id/bearbeiten'
    | '/m/upload/$session'
    | '/protokolle/$id/bearbeiten'
    | '/rechnungen/$id/bearbeiten'
  id:
    | '__root__'
    | '/'
    | '/aktivitaet'
    | '/angebote'
    | '/dokumente'
    | '/einstellungen'
    | '/kunden'
    | '/objekte'
    | '/protokolle'
    | '/rechnungen'
    | '/steuern'
    | '/stundenzettel'
    | '/werkzeuge'
    | '/angebote/$id'
    | '/angebote/neu'
    | '/einstellungen/datenbank'
    | '/kunden/$id'
    | '/kunden/neu'
    | '/objekte/$id'
    | '/objekte/neu'
    | '/protokolle/$id'
    | '/rechnungen/$id'
    | '/rechnungen/neu'
    | '/werkzeuge/schluesseluebergabe'
    | '/werkzeuge/uebergabeprotokoll'
    | '/werkzeuge/'
    | '/angebote/$id/bearbeiten'
    | '/m/upload/$session'
    | '/protokolle/$id/bearbeiten'
    | '/rechnungen/$id/bearbeiten'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AktivitaetRoute: typeof AktivitaetRoute
  AngeboteRoute: typeof AngeboteRouteWithChildren
  DokumenteRoute: typeof DokumenteRoute
  EinstellungenRoute: typeof EinstellungenRouteWithChildren
  KundenRoute: typeof KundenRouteWithChildren
  ObjekteRoute: typeof ObjekteRouteWithChildren
  ProtokolleRoute: typeof ProtokolleRouteWithChildren
  RechnungenRoute: typeof RechnungenRouteWithChildren
  SteuernRoute: typeof SteuernRoute
  StundenzettelRoute: typeof StundenzettelRoute
  WerkzeugeRoute: typeof WerkzeugeRouteWithChildren
  MUploadSessionRoute: typeof MUploadSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/werkzeuge': {
      id: '/werkzeuge'
      path: '/werkzeuge'
      fullPath: '/werkzeuge'
      preLoaderRoute: typeof WerkzeugeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stundenzettel': {
      id: '/stundenzettel'
      path: '/stundenzettel'
      fullPath: '/stundenzettel'
      preLoaderRoute: typeof StundenzettelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/steuern': {
      id: '/steuern'
      path: '/steuern'
      fullPath: '/steuern'
      preLoaderRoute: typeof SteuernRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rechnungen': {
      id: '/rechnungen'
      path: '/rechnungen'
      fullPath: '/rechnungen'
      preLoaderRoute: typeof RechnungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protokolle': {
      id: '/protokolle'
      path: '/protokolle'
      fullPath: '/protokolle'
      preLoaderRoute: typeof ProtokolleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/objekte': {
      id: '/objekte'
      path: '/objekte'
      fullPath: '/objekte'
      preLoaderRoute: typeof ObjekteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kunden': {
      id: '/kunden'
      path: '/kunden'
      fullPath: '/kunden'
      preLoaderRoute: typeof KundenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einstellungen': {
      id: '/einstellungen'
      path: '/einstellungen'
      fullPath: '/einstellungen'
      preLoaderRoute: typeof EinstellungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dokumente': {
      id: '/dokumente'
      path: '/dokumente'
      fullPath: '/dokumente'
      preLoaderRoute: typeof DokumenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebote': {
      id: '/angebote'
      path: '/angebote'
      fullPath: '/angebote'
      preLoaderRoute: typeof AngeboteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivitaet': {
      id: '/aktivitaet'
      path: '/aktivitaet'
      fullPath: '/aktivitaet'
      preLoaderRoute: typeof AktivitaetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/werkzeuge/': {
      id: '/werkzeuge/'
      path: '/'
      fullPath: '/werkzeuge/'
      preLoaderRoute: typeof WerkzeugeIndexRouteImport
      parentRoute: typeof WerkzeugeRoute
    }
    '/werkzeuge/uebergabeprotokoll': {
      id: '/werkzeuge/uebergabeprotokoll'
      path: '/uebergabeprotokoll'
      fullPath: '/werkzeuge/uebergabeprotokoll'
      preLoaderRoute: typeof WerkzeugeUebergabeprotokollRouteImport
      parentRoute: typeof WerkzeugeRoute
    }
    '/werkzeuge/schluesseluebergabe': {
      id: '/werkzeuge/schluesseluebergabe'
      path: '/schluesseluebergabe'
      fullPath: '/werkzeuge/schluesseluebergabe'
      preLoaderRoute: typeof WerkzeugeSchluesseluebergabeRouteImport
      parentRoute: typeof WerkzeugeRoute
    }
    '/rechnungen/neu': {
      id: '/rechnungen/neu'
      path: '/neu'
      fullPath: '/rechnungen/neu'
      preLoaderRoute: typeof RechnungenNeuRouteImport
      parentRoute: typeof RechnungenRoute
    }
    '/rechnungen/$id': {
      id: '/rechnungen/$id'
      path: '/$id'
      fullPath: '/rechnungen/$id'
      preLoaderRoute: typeof RechnungenIdRouteImport
      parentRoute: typeof RechnungenRoute
    }
    '/protokolle/$id': {
      id: '/protokolle/$id'
      path: '/$id'
      fullPath: '/protokolle/$id'
      preLoaderRoute: typeof ProtokolleIdRouteImport
      parentRoute: typeof ProtokolleRoute
    }
    '/objekte/neu': {
      id: '/objekte/neu'
      path: '/neu'
      fullPath: '/objekte/neu'
      preLoaderRoute: typeof ObjekteNeuRouteImport
      parentRoute: typeof ObjekteRoute
    }
    '/objekte/$id': {
      id: '/objekte/$id'
      path: '/$id'
      fullPath: '/objekte/$id'
      preLoaderRoute: typeof ObjekteIdRouteImport
      parentRoute: typeof ObjekteRoute
    }
    '/kunden/neu': {
      id: '/kunden/neu'
      path: '/neu'
      fullPath: '/kunden/neu'
      preLoaderRoute: typeof KundenNeuRouteImport
      parentRoute: typeof KundenRoute
    }
    '/kunden/$id': {
      id: '/kunden/$id'
      path: '/$id'
      fullPath: '/kunden/$id'
      preLoaderRoute: typeof KundenIdRouteImport
      parentRoute: typeof KundenRoute
    }
    '/einstellungen/datenbank': {
      id: '/einstellungen/datenbank'
      path: '/datenbank'
      fullPath: '/einstellungen/datenbank'
      preLoaderRoute: typeof EinstellungenDatenbankRouteImport
      parentRoute: typeof EinstellungenRoute
    }
    '/angebote/neu': {
      id: '/angebote/neu'
      path: '/neu'
      fullPath: '/angebote/neu'
      preLoaderRoute: typeof AngeboteNeuRouteImport
      parentRoute: typeof AngeboteRoute
    }
    '/angebote/$id': {
      id: '/angebote/$id'
      path: '/$id'
      fullPath: '/angebote/$id'
      preLoaderRoute: typeof AngeboteIdRouteImport
      parentRoute: typeof AngeboteRoute
    }
    '/rechnungen/$id/bearbeiten': {
      id: '/rechnungen/$id/bearbeiten'
      path: '/bearbeiten'
      fullPath: '/rechnungen/$id/bearbeiten'
      preLoaderRoute: typeof RechnungenIdBearbeitenRouteImport
      parentRoute: typeof RechnungenIdRoute
    }
    '/protokolle/$id/bearbeiten': {
      id: '/protokolle/$id/bearbeiten'
      path: '/bearbeiten'
      fullPath: '/protokolle/$id/bearbeiten'
      preLoaderRoute: typeof ProtokolleIdBearbeitenRouteImport
      parentRoute: typeof ProtokolleIdRoute
    }
    '/m/upload/$session': {
      id: '/m/upload/$session'
      path: '/m/upload/$session'
      fullPath: '/m/upload/$session'
      preLoaderRoute: typeof MUploadSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/angebote/$id/bearbeiten': {
      id: '/angebote/$id/bearbeiten'
      path: '/bearbeiten'
      fullPath: '/angebote/$id/bearbeiten'
      preLoaderRoute: typeof AngeboteIdBearbeitenRouteImport
      parentRoute: typeof AngeboteIdRoute
    }
  }
}

interface AngeboteIdRouteChildren {
  AngeboteIdBearbeitenRoute: typeof AngeboteIdBearbeitenRoute
}

const AngeboteIdRouteChildren: AngeboteIdRouteChildren = {
  AngeboteIdBearbeitenRoute: AngeboteIdBearbeitenRoute,
}

const AngeboteIdRouteWithChildren = AngeboteIdRoute._addFileChildren(
  AngeboteIdRouteChildren,
)

interface AngeboteRouteChildren {
  AngeboteIdRoute: typeof AngeboteIdRouteWithChildren
  AngeboteNeuRoute: typeof AngeboteNeuRoute
}

const AngeboteRouteChildren: AngeboteRouteChildren = {
  AngeboteIdRoute: AngeboteIdRouteWithChildren,
  AngeboteNeuRoute: AngeboteNeuRoute,
}

const AngeboteRouteWithChildren = AngeboteRoute._addFileChildren(
  AngeboteRouteChildren,
)

interface EinstellungenRouteChildren {
  EinstellungenDatenbankRoute: typeof EinstellungenDatenbankRoute
}

const EinstellungenRouteChildren: EinstellungenRouteChildren = {
  EinstellungenDatenbankRoute: EinstellungenDatenbankRoute,
}

const EinstellungenRouteWithChildren = EinstellungenRoute._addFileChildren(
  EinstellungenRouteChildren,
)

interface KundenRouteChildren {
  KundenIdRoute: typeof KundenIdRoute
  KundenNeuRoute: typeof KundenNeuRoute
}

const KundenRouteChildren: KundenRouteChildren = {
  KundenIdRoute: KundenIdRoute,
  KundenNeuRoute: KundenNeuRoute,
}

const KundenRouteWithChildren =
  KundenRoute._addFileChildren(KundenRouteChildren)

interface ObjekteRouteChildren {
  ObjekteIdRoute: typeof ObjekteIdRoute
  ObjekteNeuRoute: typeof ObjekteNeuRoute
}

const ObjekteRouteChildren: ObjekteRouteChildren = {
  ObjekteIdRoute: ObjekteIdRoute,
  ObjekteNeuRoute: ObjekteNeuRoute,
}

const ObjekteRouteWithChildren =
  ObjekteRoute._addFileChildren(ObjekteRouteChildren)

interface ProtokolleIdRouteChildren {
  ProtokolleIdBearbeitenRoute: typeof ProtokolleIdBearbeitenRoute
}

const ProtokolleIdRouteChildren: ProtokolleIdRouteChildren = {
  ProtokolleIdBearbeitenRoute: ProtokolleIdBearbeitenRoute,
}

const ProtokolleIdRouteWithChildren = ProtokolleIdRoute._addFileChildren(
  ProtokolleIdRouteChildren,
)

interface ProtokolleRouteChildren {
  ProtokolleIdRoute: typeof ProtokolleIdRouteWithChildren
}

const ProtokolleRouteChildren: ProtokolleRouteChildren = {
  ProtokolleIdRoute: ProtokolleIdRouteWithChildren,
}

const ProtokolleRouteWithChildren = ProtokolleRoute._addFileChildren(
  ProtokolleRouteChildren,
)

interface RechnungenIdRouteChildren {
  RechnungenIdBearbeitenRoute: typeof RechnungenIdBearbeitenRoute
}

const RechnungenIdRouteChildren: RechnungenIdRouteChildren = {
  RechnungenIdBearbeitenRoute: RechnungenIdBearbeitenRoute,
}

const RechnungenIdRouteWithChildren = RechnungenIdRoute._addFileChildren(
  RechnungenIdRouteChildren,
)

interface RechnungenRouteChildren {
  RechnungenIdRoute: typeof RechnungenIdRouteWithChildren
  RechnungenNeuRoute: typeof RechnungenNeuRoute
}

const RechnungenRouteChildren: RechnungenRouteChildren = {
  RechnungenIdRoute: RechnungenIdRouteWithChildren,
  RechnungenNeuRoute: RechnungenNeuRoute,
}

const RechnungenRouteWithChildren = RechnungenRoute._addFileChildren(
  RechnungenRouteChildren,
)

interface WerkzeugeRouteChildren {
  WerkzeugeSchluesseluebergabeRoute: typeof WerkzeugeSchluesseluebergabeRoute
  WerkzeugeUebergabeprotokollRoute: typeof WerkzeugeUebergabeprotokollRoute
  WerkzeugeIndexRoute: typeof WerkzeugeIndexRoute
}

const WerkzeugeRouteChildren: WerkzeugeRouteChildren = {
  WerkzeugeSchluesseluebergabeRoute: WerkzeugeSchluesseluebergabeRoute,
  WerkzeugeUebergabeprotokollRoute: WerkzeugeUebergabeprotokollRoute,
  WerkzeugeIndexRoute: WerkzeugeIndexRoute,
}

const WerkzeugeRouteWithChildren = WerkzeugeRoute._addFileChildren(
  WerkzeugeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AktivitaetRoute: AktivitaetRoute,
  AngeboteRoute: AngeboteRouteWithChildren,
  DokumenteRoute: DokumenteRoute,
  EinstellungenRoute: EinstellungenRouteWithChildren,
  KundenRoute: KundenRouteWithChildren,
  ObjekteRoute: ObjekteRouteWithChildren,
  ProtokolleRoute: ProtokolleRouteWithChildren,
  RechnungenRoute: RechnungenRouteWithChildren,
  SteuernRoute: SteuernRoute,
  StundenzettelRoute: StundenzettelRoute,
  WerkzeugeRoute: WerkzeugeRouteWithChildren,
  MUploadSessionRoute: MUploadSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
